### PR TITLE
Fix compatibility with Symfony 5.0

### PR DESCRIPTION
**Pull request by davnavarro**

### CODE REVIEW

**Comment by sampart** [comment]
Hi @davnavarro, thanks for contributing!  I presume that this change doesn't work in older versions of Symfony?  Do you know which versions it works with?

**Comment by davnavarro** [comment]
Hi @sampart,
Please, give me some time and I check
;)

**Comment by davnavarro** [comment]
Hi @sampart,
This change works (tested) in versions 4.3, 4.4 and 5.0
In previous versions I could not verify.

**Comment by sampart** [comment]
Many thanks for this. Looking at the link, this change will work in Symfony 3.3 and up.  Therefore, we'd need to change `composer.json` as part of this (and make it a major version bump when releasing).  Please could you either...
* Update this PR to include the necessary changes to `composer.json`: `"symfony/framework-bundle": ">=3.3"`, and `"php": "^5.5.9|>=7.0.8"`
* Or, if you're feeling keen, this would be a great case for a [maintained fork](https://github.com/whiteoctober/WhiteOctoberTCPDFBundle/issues/57), so might you be interested in setting up a fork for sf 3.3 and above? (See linked issue for details)

**Comment by davnavarro** [comment]
Hi @sampart,
I hadn't done this before ...
Please, when you can check this: [QipsiusTCPDFBundle(https://github.com/Qipsius/QipsiusTCPDFBundle)
Any help and guidance will be welcome.

**Comment by sampart** [comment]
Thanks so much for taking this on, @davnavarro - your fork looks great.  I've added a note to the top of the README for this repo suggesting that people use your fork.

I recommend that you now look through the [issues](https://github.com/whiteoctober/WhiteOctoberTCPDFBundle/issues) logged against this project and post a comment if any are resolved by your fork.  This may also give you ideas as to what changes to make next in your onward development.

Thanks again for your work here.

**Pull request closed without merging**
